const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let estado=null;
$('#link-galeria').href=`${location.protocol}//${location.hostname}:8080`;
function aviso(m,erro=false){const e=$('#aviso');e.textContent=m;e.className=`aviso visivel${erro?' erro':''}`;clearTimeout(aviso.timer);aviso.timer=setTimeout(()=>e.className='aviso',5200)}
async function api(url,o={}){const r=await fetch(url,o),d=await r.json().catch(()=>({erro:'Resposta inválida do servidor.'}));if(!r.ok)throw new Error(d.erro||'Não foi possível concluir.');return d}
function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML}
function mostrarPainel(d){estado=d;$('#entrada').classList.add('oculto');$('#painel').classList.remove('oculto');$('#nome-aluno').textContent=d.estudio.nome||d.aluno;const f=$('#form-estudio');f.estudio.value=d.estudio.estudio||'';f.lema.value=d.estudio.lema||'';f.cor.value=d.estudio.cor||'#6d5dfc';$('[data-contagem="lema"]').textContent=f.lema.value.length;$('#contador').textContent=d.jogos.length;$('#lista-jogos').innerHTML=d.jogos.length?d.jogos.map(j=>`<div class="item-jogo"><strong>${esc(j.titulo)}</strong><span>${esc(j.engine)} · ${esc(j.slug)}</span></div>`).join(''):'<div class="vazio">Você ainda não publicou nenhum jogo.</div>'}
async function carregar(){const a=await api('/api/alunos');$('#aluno').innerHTML='<option value="">Selecione seu nome</option>'+a.map(x=>`<option value="${x.slug}">${esc(x.nome)}</option>`).join('');try{mostrarPainel(await api('/api/me'))}catch(_){}}
$('#form-entrada').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/entrar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aluno:$('#aluno').value,codigo:$('#codigo').value})});mostrarPainel(await api('/api/me'))}catch(x){aviso(x.message,true)}});
$('#sair').addEventListener('click',async()=>{await api('/api/sair',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.reload()});
$$('.abas button').forEach(b=>b.addEventListener('click',()=>{$$('.abas button,.secao').forEach(e=>e.classList.remove('ativa'));b.classList.add('ativa');$('#'+b.dataset.alvo).classList.add('ativa')}));
$('[name="lema"]').addEventListener('input',e=>$('[data-contagem="lema"]').textContent=e.target.value.length);
$('#engine').addEventListener('change',e=>{const x=e.target.value;$('#campo-pacote').classList.toggle('oculto',x==='link');$('#campo-scratch').classList.toggle('oculto',x!=='scratch');$('#campo-url').classList.toggle('oculto',x!=='link');$('#campo-pacote input').required=['html','construct','pygame'].includes(x)});
for(const[s,r]of[['#form-estudio','/api/estudio'],['#form-jogo','/api/jogos']]){$(s).addEventListener('submit',async e=>{e.preventDefault();$('#carregando').classList.remove('oculto');try{const d=await api(r,{method:'POST',body:new FormData(e.target)});aviso(d.mensagem);mostrarPainel(await api('/api/me'));if(s==='#form-jogo')e.target.reset()}catch(x){aviso(x.message,true)}finally{$('#carregando').classList.add('oculto')}})}
carregar().catch(e=>aviso(e.message,true));
